baudrate = 19200
token = '1325955552:AAHQJzvhu-IhcMpsVGX5dUsfXTJ7fFECoJs'

# Путь к логу, пишется на HDD
log_path = '/home/pi/hdd_drive/pavlovsk_doc/debug/debug_log'
# Путь в БД, пишется на HDD

raspi_bd = '/home/pi/hdd_drive/pavlovsk_doc/bd/raspi_doc.db'
table_regular_values = 'g_val' # Имя таблицы для быстрых значений


# Расположение таблиц ModBus
mb_table_3516 = '/home/pi/Documents/PythonScripts/raspi_doc/mb_table/doc_3516_mb.txt'
mb_table_3520 = '/home/pi/Documents/PythonScripts/raspi_doc/mb_table/doc_3520_mb.txt'

# Отсюда берутся регистры с состояниями защит
protections_3516 = '/home/pi/Documents/PythonScripts/raspi_doc/protections_3516.txt'
protections_3520 = '/home/pi/Documents/PythonScripts/raspi_doc/protections_3520.txt'

# Состояния двигателя
engine_states = ('Init', 'Ready', 'NotReady', 'Prestart', 'Cranking', 'Pause', 'Starting', 'Running', 'Loaded', 'Soft unld', 'Cooling', 'Stop', 'Shutdown', 'Ventil', 'EmergMan', 'Cooldown', 'Offload', 'Soft load', 'WaitStop', 'Warming', 'SDVentil', 'WD test', 'GasVTest', 'StrtCndWai')

# Состояния АВГ
breaker_states = ('Init', 'BrksOff', 'IslOper', 'MainsOper', 'ParalOper', 'RevSync', 'Synchro', 'MainsFlt', 'ValidFlt', 'MainsRet', 'MultIslOp', 'MultParOp', 'EmergMan', 'StrUpSync', None)

# Значения уровней защиты
protect_levels = ('inactive', 'N/A', 'active, confirmed', 'active, but blocked or delay still running', 'previously active, not confirmed yet', 'N/A','active, not confirmed yet', 'active, not confirmed yet, blocked')

# Значения уровней ошибок датчиков
sensfails = ('Sensor failure not active', 'Sensor failure active, confirmed', 'Sensor failure previously active, not confirmed yet', 'Sensor failure active, not confirmed yet')

# Группы переменных для постоянного опроса и записи в БД
regular_values = (
'Analog CU',
'AnalogInputs 1',
'AnalogInputs 2',
'AnalogInputs 3',
'AnalogInputs 4',
'AnalogInputs 5',
'Bus values',
'Engine values',
'Gener values',
'Bin inputs CU',
'Bin outputs CU',
'Binary Inputs',
'Binary Outputs'
)

# Группы переменных для опроса и записи в БД при изменении
values_if_changed = (
'Analog protect',
'Basic settings',
'Comms settings',
'Engine params',
'Engine protect',
'Gener protect',
'Load shedding',
'Mains protect',
'PLC',
'ProcessControl',
'Pwr management',
'Sync/Load ctrl',
'Volt/PF ctrl'
)

# Перечень игнорируемых при опросе параметров
val_ignore_list = (
'Genset1 Gen V unbal',
'Max ER Temp',
'Load char', 
'Load char L1', 
'Load char L2', 
'Load char L3',
'N/A',
'CAN2emptDetect',
'D+ function',
'Bin selector 1', 
'Bin selector 2', 
'Bin selector 3', 
'Bin selector 4',
'ResetActAlarms',
'ForceBlock1Del',
'ForceBlock2Del',
'ForceBlock3Del',
'RunOnlyBlkDel1',
'RunOnlyBlkDel2',
'RunOnlyBlkDel3',
'BinInp delay 1',
'BinInp delay 2',
'BinInp delay 3',
'RunHoursSource',
'CB ctrl mode',
'ImpCountDef1',
'ImpCountDef2',
'ImpCountDef3',
'ImpCountDef4',
'LossEngPwr del',
'BOC LossEngPwr',
'ContrInitMode',
'UserBtn pulse',
'ConvCoefPulse1',
'ConvCoefPulse2',
'ConvCoefPulse3',
'ConvCoefPulse4',
'#PwrBandContr1',
'#PwrBandContr2',
'#PwrBandContr3',
'#PwrBandContr4',
'#RunHrsMaxDiff',
'#MinRunPower 1',
'#MinRunPower 2',
'#MinRunPower 3',
'#SlowStopDel',
'#NextStopDel',
'#OverldNextDel',
'#NextStrt del',
'#%LdResStop 1',
'#%LdResStop 2',
'#%LdResStop 3',
'#%LdResStop 4',
'#%LdResStrt 1',
'#%LdResStrt 2',
'#%LdResStrt 3',
'#%LdResStrt 4',
'#LoadResStop 1',
'#LoadResStop 2',
'#LoadResStop 3',
'#LoadResStop 4',
'#LoadResStrt 1',
'#LoadResStrt 2',
'#LoadResStrt 3',
'#LoadResStrt 4',
'#SysAMFstopDel',
'#SysAMFstrtDel',
'#PriorAutoSwap',
'#Pwr mgmt mode',
'#Neutral cont',
'#SysPwrFactor',
'',
'D+',
'Cyl Temp 1 Yel',
'Cyl Temp 2 Yel',
'Cyl Temp 3 Yel',
'Cyl Temp 4 Yel',
'Cyl Temp 5 Yel',
'Cyl Temp 6 Yel',
'Cyl Temp 7 Yel',
'Cyl Temp 8 Yel',
'Cyl Temp 9 Yel',
'Cyl Temp 10 Yel',
'Cyl Temp 11 Yel',
'Cyl Temp 12 Yel',
'Cyl Temp 13 Yel',
'Cyl Temp 14 Yel',
'Cyl Temp 15 Yel',
'Cyl Temp 16 Yel',
'Cyl Temp 17 Yel',
'Cyl Temp 18 Yel',
'Cyl Temp 19 Yel',
'Cyl Temp 20 Yel',
'Cyl Temp 1 Red',
'Cyl Temp 2 Red',
'Cyl Temp 3 Red',
'Cyl Temp 4 Red',
'Cyl Temp 5 Red',
'Cyl Temp 6 Red',
'Cyl Temp 7 Red',
'Cyl Temp 8 Red',
'Cyl Temp 9 Red',
'Cyl Temp 10 Red',
'Cyl Temp 11 Red',
'Cyl Temp 12 Red',
'Cyl Temp 13 Red',
'Cyl Temp 14 Red',
'Cyl Temp 15 Red',
'Cyl Temp 16 Red',
'Cyl Temp 17 Red',
'Cyl Temp 18 Red',
'Cyl Temp 19 Red',
'Cyl Temp 20 Red',
'Cyl Temp 1 Del',
'Cyl Temp 2 Del',
'Cyl Temp 3 Del',
'Cyl Temp 4 Del',
'Cyl Temp 5 Del',
'Cyl Temp 6 Del',
'Cyl Temp 7 Del',
'Cyl Temp 8 Del',
'Cyl Temp 9 Del',
'Cyl Temp 10 Del',
'Cyl Temp 11 Del',
'Cyl Temp 12 Del',
'Cyl Temp 13 3Del',
'Cyl Temp 14 Del',
'Cyl Temp 15 Del',
'Cyl Temp 16 Del',
'Cyl Temp 17 Del',
'Cyl Temp 18 Del',
'Cyl Temp 19 Del',
'Cyl Temp 20 Del',
'Cyl Temp1 Yel',
'Cyl Temp2 Yel',
'Cyl Temp3 Yel',
'Cyl Temp4 Yel',
'Cyl Temp5 Yel',
'Cyl Temp6 Yel',
'Cyl Temp7 Yel',
'Cyl Temp8 Yel',
'Cyl Temp9 Yel',
'Cyl Temp10 Yel',
'Cyl Temp11 Yel',
'Cyl Temp12 Yel',
'Cyl Temp13 Yel',
'Cyl Temp14 Yel',
'Cyl Temp15 Yel',
'Cyl Temp16 Yel',
'Cyl Temp17 Yel',
'Cyl Temp18 Yel',
'Cyl Temp19 Yel',
'Cyl Temp20 Yel',
'Cyl Temp1 Red',
'Cyl Temp2 Red',
'Cyl Temp3 Red',
'Cyl Temp4 Red',
'Cyl Temp5 Red',
'Cyl Temp6 Red',
'Cyl Temp7 Red',
'Cyl Temp8 Red',
'Cyl Temp9 Red',
'Cyl Temp10 Red',
'Cyl Temp11 Red',
'Cyl Temp12 Red',
'Cyl Temp13 Red',
'Cyl Temp14 Red',
'Cyl Temp15 Red',
'Cyl Temp16 Red',
'Cyl Temp17 Red',
'Cyl Temp18 Red',
'Cyl Temp19 Red',
'Cyl Temp20 Red',
'Cyl Temp1 Del',
'Cyl Temp2 Del',
'Cyl Temp3 Del',
'Cyl Temp4 Del',
'Cyl Temp5 Del',
'Cyl Temp6 Del',
'Cyl Temp7 Del',
'Cyl Temp8 Del',
'Cyl Temp9 Del',
'Cyl Temp10 Del',
'Cyl Temp11 Del',
'Cyl Temp12 Del',
'Cyl Temp13 3Del',
'Cyl Temp14 Del',
'Cyl Temp15 Del',
'Cyl Temp16 Del',
'Cyl Temp17 Del',
'Cyl Temp18 Del',
'Cyl Temp19 Del',
'Cyl Temp20 Del',
'#SysLdCtrl PtM',
'#SysPFCtrl PtM',
'#SysBaseLoad',
'#PwrBnChngDlUp',
'#PwrBnChngDlDn',
'ConvCoefPulse5',
'ConvCoefPulse6',
'ConvCoefPulse7',
'ConvCoefPulse8',   
'ImpCountDef5',
'ImpCountDef6',
'ImpCountDef7',
'ImpCountDef8',
'ServiceTimeSd',    
'AFT registr',
'Act Pwr Band',
'DPF status',
'Force value 1',
'Force value 10',
'Force value 11',
'Force value 12',
'Force value 13',
'Force value 14',
'Force value 15',
'Force value 16',
'Force value 2',
'Force value 3',
'Force value 4',
'Force value 5',
'Force value 6',
'Force value 7',
'Force value 8',
'Force value 9',
'Gen-set name',
'SDVentil time',
'Latitude',
'Longitude',
'Next Pwr Band',
'NextDate1-4',
'NextDate13-16',
'NextDate5-8',
'NextDate9-12',
'NextTime1-4',
'NextTime13-16',
'NextTime5-8',
'NextTime9-12',
'PasswordDecode',
'PulseCounter 2',
'PulseCounter 3',
'PulseCounter 4',
'RunHoursBase',
'StatusDW',
'TimerChannel 1',
'TimerChannel 2',
'TimerChannel 3',
'TimerChannel 4',
'TimerChannel 5',
'TimerChannel 6',
'TimerChannel 7',
'TimerChannel 8',
'TimerChannel 9',
'TimerChannel10',
'TimerChannel11',
'TimerChannel12',
'TimerChannel13',
'TimerChannel14',
'TimerChannel15',
'TimerChannel16',
'netPgnomPh',
'StatLdShed',
'SystLoadCtrl',
'SystPfCtrl',
'CT ratio sec',
'EarthFltCurCTs',
'Vg InpRangeSel',
'Vb InpRangeSel',
'FixVoltProtSel',
'Nominal freq',
'ControllerMode',
'FltRes GoToMAN',
'Local buttons',
'LB/UART Log',
'SHxOcol Detect',
'DispBklStrtOff',
'Cooling speed',
'Cooldown optim',
'CoolDnAfterBOC',
'GasVTest',
'Synchro enable',
'SysBaseLdMode',
'SysBasePFMode',
'BusMeasError',
'SpeedRegChar',
'Freq reg loop',
'AVRRegChar',
'AutoLd recon',
'Ld shed active',
'ECU Diag',
'Pwr management',
'Priority ctrl',
'Sync type'
)

# Перечень параметров для чтения функцией read_long()
var_long_list = (
'Gas Meter',
'Run hours',
'TotRunPact P',
'TotRunPact Q',
'kVAhours',
'kVArhours',
'kWhours'
)
